---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system